#! /bin/sh

alias fucking='sudo'
alias please='sudo'

alias ls='eza -A --icons=always'
alias ll='eza -Alm --git --icons=always --no-user'
alias lr='eza -ARlm --git --icons=always --no-user'
alias tree='eza -lm --git --icons=always --no-user --tree'
alias du='du -kh'

alias c='$IDE .'
alias e='edit-text'
compdef e=edit-text
alias f='fork .'
alias g='git'
compdef g=git
alias h='history 0 | grep'
alias o='open'
alias rk='noglob rake'
alias sc='shellcheck'

alias dc='docker compose'
alias dcd='docker compose down --remove-orphans'

alias gr='noglob rake --rakelib ~/.rake --rakefile none'

alias be='bundle exec'
alias ber='noglob bundle exec rake'
alias bert='bundle exec rake -T'
alias berd='bundle exec rake -D'
alias berta='bundle exec rake -T -A'
alias bdep='bundle list --paths | ruby --disable-all -n -e"puts(File.basename(\$_))"'

alias fspec='rspec --order defined --fail-fast --format d'
alias rcop='rubocop -D -E -S'
alias rpretty='stree write --plugins=plugin/single_quotes "**/*.{ru,rb,rake}"'
