# .zshenv
#
# zsh user init sequence:
# ~/.zshenv   - in any case
# ~/.zprofile - except: non-login + non-interactive
# ~/.zshrc    - in every interactive case

. ~/.local/init/zshenv.zsh

export PS1='%~ :'
export LANG=en_GB.utf-8 LANGUAGE=en_GB.utf-8 LC_ALL=en_GB.utf-8
export BREW_PATH="/opt/homebrew" HOMEBREW_NO_AUTO_UPDATE=1

path_prepend "$BREW_PATH/sbin" PATH
path_prepend "$BREW_PATH/bin" PATH
path_prepend "$HOME/bin" PATH

export GPG_TTY=$(tty)
export GZIP=-9
export GOPATH=$HOME/prj/go

try_source ~/.local/init/local/zshenv
