# .zshrc
# all interactive settings

# setup jobs
setopt notify
setopt long_list_jobs

# setup colors
autoload -Uz colors
colors
export CLICOLOR=1 LSCOLORS=cxfxdxdxbxExExBxBxCxCx
export LS_COLORS="di=32:ln=35:so=33:pi=33:ex=31:bd=1;34:cd=1;34:su=1;31:sg=1;31:tw=1;32:ow=1;32"
export BAT_THEME='base16'

# setup history
export HISTFILE=~/.histfile HISTSIZE=1000 SAVEHIST=1000
setopt extended_history
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_verify

# setup completion
fpath=($HOME/bin/comp $BREW_PATH/share/zsh/functions $BREW_PATH/share/zsh/site-functions $fpath)
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=1
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]} l:|=* r:|=*'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
autoload -Uz compinit
autoload -Uz complist
compinit

setopt auto_list
setopt complete_aliases
setopt list_ambiguous
setopt no_list_beep
setopt list_packed
setopt list_types

# setup edit
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
bindkey "\e[1;3C" forward-word
bindkey "\e[1;3D" backward-word
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line

autoload -Uz select-word-style
select-word-style bash

# setup cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent

# setup prompt
setopt prompt_subst
# setopt prompt_percent
autoload -Uz promptinit
promptinit
if [ "$TERM_PROGRAM" = "iTerm.app" ]
then
  PROMPT=''
  RPROMPT='%(?,,❗%F{yellow}%B%?%b%f)'
else
  PROMPT='%~ ▸'
fi

try_source "$BREW_PATH/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
try_source "$BREW_PATH/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

try_source ~/.local/init/iterm2_shell_integration.zsh
source ~/.local/init/lib.zsh
source ~/.local/init/alias

eval "$(fzf --zsh)"
export FZF_DEFAULT_OPTS='--height=60% --highlight-line --border=rounded --border-label-pos=4'

export EDITOR='mate -w' GEM_EDITOR=mate
export IDE=code BROWSER=Safari

try_source ~/.local/init/local/zshrc
welcome
