tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'thoughtbot/formulae'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/openssh'
brew 'autoconf'
brew 'automake'
brew 'cloc'
brew 'git'
brew 'git-extras'
brew 'gnupg'
brew 'hr'
brew 'libtool'
brew 'htop-osx'
brew 'imagesnap'
brew 'pkg-config'
brew 'openssl'
brew 'libevent'
brew 'libgpg-error'
brew 'libksba'
brew 'readline'
brew 'postgresql'
brew 'libpqxx'
brew 'libyaml'
brew 'nmap'
brew 'pwgen'
brew 'rbenv', args: ['HEAD']
brew 'rbenv-gem-rehash'
brew 'ruby-build'
brew 'ruby-install'
brew 'spark'
brew 'terminal-notifier'
brew 'tmux'
brew 'watch'
brew 'zsh'
brew 'thoughtbot/formulae/rcm'
brew 'tree'
brew 'tag'
cask 'iterm2'
# cask 'virtualbox'
# cask 'vagrant'
cask 'firefox'
cask 'slack'
cask 'google-chrome'
cask 'google-drive'
cask 'gimp'
cask 'keka'

# don't forget to `sudo dscl . change /users/$USER UserShell /bin/bash $(which zsh)`
