
# source file only if file exists
try_source() { [ -f "$1" ] && . $@ || return 1 }

# execute file only if file exists
try_call() { [ -x "$1" ] && $@ || return 1 }

setopt beep

try_source "$BREW_PATH/opt/asdf/libexec/asdf.sh"
