
# setup jobs
setopt notify
setopt long_list_jobs

# setup colors
autoload -U colors
colors
export CLICOLOR=1 LSCOLORS=cxfxdxdxbxExExBxBxCxCx
export LS_COLORS="di=32:ln=35:so=33:pi=33:ex=31:bd=1;34:cd=1;34:su=1;31:sg=1;31:tw=1;32:ow=1;32"

# setup history
export HISTFILE=~/.histfile HISTSIZE=1000 SAVEHIST=1000
setopt extended_history
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt hist_ignore_space
setopt hist_save_no_dups
setopt hist_verify
# setopt append_history
# setopt inc_append_history
# setopt no_hist_beep

# history search:
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "\e[A" history-beginning-search-backward-end
bindkey "\e[B" history-beginning-search-forward-end

# setup completion
fpath=($HOME/.local/completion $BREW_PATH/share/zsh/functions $BREW_PATH/share/zsh/site-functions $fpath)
zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select=1
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]} l:|=* r:|=*'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
autoload -Uz compinit
autoload -U complist
compinit

setopt auto_list
setopt complete_aliases
setopt list_ambiguous
setopt no_list_beep
setopt list_packed
setopt list_types

# setup edit
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line

autoload -U select-word-style
select-word-style bash

# setup cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent
setopt correct

# setup prompt
setopt prompt_subst
setopt prompt_percent
autoload -U promptinit
promptinit
PROMPT=''
RPROMPT='%(?,,%K{red}%F{white}%B %? %b%f%k)'

try_source "$BREW_PATH/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
try_source "$BREW_PATH/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source ~/.local/init/iterm2_shell_integration.zsh
source ~/.local/init/lib.zsh
source ~/.local/init/alias
try_source ~/.zshrc.local
try_source ~/.config/broot/launcher/bash/br

welcome
