#! /bin/zsh

# setup language
export LANG=en_GB.utf-8
export LC_ALL=en_GB.utf-8

# setup jobs
setopt notify
setopt long_list_jobs

source ~/.local/init/lib.zsh

[[ -o interactive ]] && {
  # setup colors
  autoload -U colors
  colors
  export CLICOLOR=1
  export LSCOLORS=cxfxdxdxbxExExBxBxCxCx
  export LS_COLORS="di=32:ln=35:so=33:pi=33:ex=31:bd=1;34:cd=1;34:su=1;31:sg=1;31:tw=1;32:ow=1;32"

	# setup history
	export HISTFILE=~/.histfile
	export HISTSIZE=100000
	export SAVEHIST=100000
	setopt extended_history
	setopt share_history
  setopt hist_expire_dups_first
	setopt hist_ignore_dups
  setopt hist_ignore_all_dups
  setopt hist_find_no_dups
	setopt hist_ignore_space
  setopt hist_save_no_dups
  setopt hist_verify
  # setopt append_history
  # setopt inc_append_history
  # setopt no_hist_beep

	# history search:
	autoload -U history-search-end
	zle -N history-beginning-search-backward-end history-search-end
	zle -N history-beginning-search-forward-end history-search-end
	bindkey "\e[A" history-beginning-search-backward-end
	bindkey "\e[B" history-beginning-search-forward-end

	# setup completion
  # fpath=($HOME/.zsh/completions $fpath)
  zstyle ':completion:*' completer _complete _ignored _approximate
  zstyle ':completion:*' max-errors 2
  zstyle ':completion:*' menu select=1
  zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]} l:|=* r:|=*'
  zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
  autoload -Uz compinit
  autoload -U complist
  compinit

  setopt auto_list
  setopt complete_aliases
  setopt list_ambiguous
  setopt no_list_beep
  setopt list_packed

  # misc
	setopt beep

	# setup edit
	autoload -Uz edit-command-line
	zle -N edit-command-line
	bindkey '^X^E' edit-command-line

	# setup cd
	setopt auto_pushd
	setopt pushd_ignore_dups
	setopt pushd_silent
	setopt correct

	# setup prompt
	setopt prompt_subst
	setopt prompt_percent
	autoload -U promptinit
	promptinit
	export PS1='%~$ '
  PROMPT='%(?,,%K{red}%F{white}%B %? %b%f%k)'
  WORDCHARS='*?_-.[]~=&;!#$%^(){}<>/@'
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=blue'
  [[ "$TERM_PROGRAM" != 'iTerm.app' ]] && export PS1='%~$ '

  may_source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source ~/.local/init/iterm2_shell_integration.zsh
  source ~/.local/init/ilib.zsh
  source ~/.local/init/alias
}

export EDITOR='mate -w'
export GEM_EDITOR=mate
export GZIP=-9
export GOPATH=$HOME/prj/go
export GPG_TTY=$(tty)
export HOMEBREW_NO_AUTO_UPDATE=1
export BAT_THEME='base16'
export PATH="$HOME/bin:/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

source ~/.local/init/aws
may_source ~/.zshrc.local
may_source /opt/homebrew/opt/asdf/libexec/asdf.sh

[[ -o interactive ]] && may_source ~/.config/broot/launcher/bash/br

welcome